### ISSUE TITLE
Crash when using cmd

### ISSUE THREAD

**Issue by emansih** [snobu/destreamer#117]
Hi, I am using cmd to download videos. 

When I run the following, the Chrome browser pops up for a brief second before crashing.
```
destreamer.cmd -i https://web.microsoftstream.com/video/xxxxxx
```

Some logs:
```
Using ffmpeg version 4.2.2 Copyright (c) 2000-2019 the FFmpeg developers

.token_cache not found.

Launching headless Chrome to perform the OpenID Connect dance...
Navigating to login page...
Error: Page crashed!
    at Page._onTargetCrashed (C:\Users\User\destreamer\node_modules\puppeteer\lib\Page.js:213:24)
    at CDPSession.<anonymous> (C:\Users\User\destreamer\node_modules\puppeteer\lib\Page.js:122:56)
    at CDPSession.emit (events.js:315:20)
    at CDPSession._onMessage (C:\Users\User\destreamer\node_modules\puppeteer\lib\Connection.js:200:12)
    at Connection._onMessage (C:\Users\User\destreamer\node_modules\puppeteer\lib\Connection.js:112:17)
    at WebSocket.<anonymous> (C:\Users\User\destreamer\node_modules\puppeteer\lib\WebSocketTransport.js:44:24)
    at WebSocket.onMessage (C:\Users\User\destreamer\node_modules\ws\lib\event-target.js:120:16)
    at WebSocket.emit (events.js:315:20)
    at Receiver.receiverOnMessage (C:\Users\User\destreamer\node_modules\ws\lib\websocket.js:789:20)
    at Receiver.emit (events.js:315:20)


Unhandled error!
Timeout or fatal error, please check your downloads directory and try again
```

There is nothing in my videos directory. 

npm version: 6.14.4
node version: v14.0.0
destreamer version: 94b6da7fae3cf21171f633abe4f33930065725b2
Windows 10 build 18363

Thanks for any help!

**Comment by snobu** [comment]
For some reason the Chromium build that puppeteer pulls down from npm crashes on your system. Instead of debugging that (which may prove difficult) you could try plugging in your own browser (Chrome or the Chromium-based Microsoft Edge should both work).

See https://github.com/snobu/destreamer/issues/32#issuecomment-606591979 for details.

**Comment by emansih** [comment]
still crashes with the same message even after changing my browser. i have tried powershell and cmd

**Comment by snobu** [comment]
Really wish i could help here, but since i'm unable to reproduce i don't really know where to begin. Can you run `npm run test` successfully?

Try adding ` --disable-gpu` and `--no-sandbox` to puppeteer, maybe it helps. Don't forget to `npm run build` after.
https://github.com/snobu/destreamer/blob/master/src/destreamer.ts#L57
```
['arg1', 'arg2', ...]
```

Also, if you're running in a VM make sure it has plenty of memory, Chromium doesn't joke around.

**Comment by emansih** [comment]
interesting.... adding the `--no-sandbox` argument works now!

**Comment by snobu** [comment]
Alright, i'm going to make that the default. @kylon, @lukaarma, anyone immediate downside to that? I don't see any.

**Comment by emansih** [comment]
Downside is breaking chrome's security model since there is no sandbox

**Comment by snobu** [comment]
Should be fine, both the app and the browser window are controlled by the user and the execution time is very limited.

Alternatively, we could catch that page error and try to launch puppeteer again with `--no-sandbox`.

**Comment by lukaarma** [comment]
It should be fine since we check that we are not admin/root and we visit only Microsoft pages...so I think this can be a fix but if we can found another fix down the line i would prefer to re enable sandboxing

**Comment by snobu** [comment]
Chromium is now launched with -no-sandbox because YOLO.
