### ISSUE TITLE
Save login and password

### ISSUE THREAD

**Issue by mavink** [snobu/destreamer#188]
Please add an option to save the login and password. Puppeteer supports autofilling logins and passwords - https://stackoverflow.com/questions/50074799/how-to-login-in-puppeteer

**Comment by lukaarma** [comment]
We already support username auto filling.

For the password auto filling:
- In the latest version use the option '-k' and after the first login were you will say yes to "remember me" and from then on you won't need to insert username/pswd
- we won't ever put password as an option for the command because it's extremely insecure to leave your password in your terminal history.
If we ever implement some sort of password auto filling it will be at runtime anyway and probably we would add a system keyring

**Comment by mavink** [comment]
I do not think it is wise to impose your views on security on others. After all Firefox and Chrome auto save passwords. Anyone who opens that browser can go to saved logins and see the passwords. Very few people protect their passwords with a master password. 

The reason you are giving does not make sense. By that standard puppeteer should not have an option to send the password to Chrome. And Chrome should not have an option to accept passwords in headless mode.

At least can you enable headless Chrome to offer to save the usernames and passwords? Headless Chrome is not attempting to save the passwords.

**Comment by lukaarma** [comment]
> After all Firefox and Chrome auto save passwords. Anyone who opens that browser can go to saved logins and see the passwords.

The password in Google chrome are protected by your Google password, I don't know for Firefox

> By that standard puppeteer should not have an option to send the password to Chrome. And Chrome should not have an option to accept passwords in headless mode

Puppeteer doesn't have a way to specifically send the password and chrome doesn't have a specific way to revive password when controlled by automated software, it's just "normal" I/O that it's needed to automate the browser and you can't filter out password specifically

And even if you ignore the security concerns of having a plain text password in your terminal history we will can't be sure of what login procedure is there fore every possible Tennant that Microsoft supports. There are so many different login procedures that we can't automate it in a reliable way.

> At least can you enable headless Chrome to offer to save the usernames and passwords? Headless Chrome is not attempting to save the passwords.

I don't know what you mean with this phrase but if you want to run chrome in headless mode after you change the code to do what you want you are free to do so by passing the "headless: true" flag to puppeteer

**Comment by emmanuel-e** [comment]
Okay can you add these two options to puppeteer.launch() in destreamer.ts?

```
		userDataDir: '.\\profile',
		ignoreDefaultArgs: ["--enable-automation"],
```


to

```

    const browser = await puppeteer_1.default.launch({
        executablePath: PuppeteerHelper_1.getPuppeteerChromiumPath(),
        headless: false,
        args: [
            '--disable-dev-shm-usage',
            '--fast-start',
            '--no-sandbox'
        ]
    });
```

to make it like this:



```

    const browser = await puppeteer_1.default.launch({
        executablePath: PuppeteerHelper_1.getPuppeteerChromiumPath(),
        headless: false,
	userDataDir: '.\\profile',
	ignoreDefaultArgs: ["--enable-automation"],
        args: [
            '--disable-dev-shm-usage',
            '--fast-start',
            '--no-sandbox'
        ]
    });
```

The first option enables a working profile directory for chrome inside the destreamer folder so that the profile can be reused. Otherwise puppeteer creates a random temporary profile directory on every launch.

The second argument allows chrome to prompt to save passwords etc. Control from puppeteer works as intended, no issues. 

Thanks!

p.s. Is the --no-sandbox argument necessary?

**Comment by mavink** [comment]
Okay can you add these two options to puppeteer.launch() in destreamer.ts?

```
		userDataDir: '.\\profile',
		ignoreDefaultArgs: ["--enable-automation"],
```


to

```

    const browser = await puppeteer_1.default.launch({
        executablePath: PuppeteerHelper_1.getPuppeteerChromiumPath(),
        headless: false,
        args: [
            '--disable-dev-shm-usage',
            '--fast-start',
            '--no-sandbox'
        ]
    });
```

to make it like this:



```

    const browser = await puppeteer_1.default.launch({
        executablePath: PuppeteerHelper_1.getPuppeteerChromiumPath(),
        headless: false,
	userDataDir: '.\\profile',
	ignoreDefaultArgs: ["--enable-automation"],
        args: [
            '--disable-dev-shm-usage',
            '--fast-start',
            '--no-sandbox'
        ]
    });
```

The first option enables a working profile directory for chrome inside the destreamer folder so that the profile can be reused. Otherwise puppeteer creates a random temporary profile directory on every launch.

The second argument allows chrome to prompt to save passwords etc. Chrome requires the windows password to show saved passwords. Control from puppeteer works as intended, no issues. 

Thanks!

p.s. Is the --no-sandbox argument necessary?

**Comment by lukaarma** [comment]
https://github.com/snobu/destreamer/blob/master/README.md#usage

we already have a '--keepLoginCookies, -k' option that does exactly that, no need to save the password in chrome. We just need the cookie created after 'remember me'

**Comment by mavink** [comment]
Okay I can see that you've added a commit on July 19, while I'm using the previous version. where you do use userDataDir.
Thats good.

So can you enable to second option ignoreDefaultArgs: ["--enable-automation"] 

You could add an another command line option to enable it.

Or is there a reason why you don't want puppeteer Chrome to also autofill and save passwords? My kid's username is 52 characters long. By the time they type it puppeteer times out and closes Chrome. After all they're just learning to type on a keyboard. That's why autofill in puppeteer Chrome is important. Microsoft sometimes decides to ask you to login again randomly. Maybe because they're signed in to many devices.

What do you think?

**Comment by mavink** [comment]
I've also made a GUI to simplify things. 
![image](https://user-images.githubusercontent.com/5507645/88385623-4c93d280-cdcc-11ea-9b44-f0aeb3e1f77e.png)

It works well if you let the Chrome GUI save the passwords.

**Comment by lukaarma** [comment]
> By the time they type it puppeteer times out and closes Chrome

They have 2,5 min to fill in they data and that can be increased here
https://github.com/snobu/destreamer/blob/ddecd9e2bc212c091fb0295882bc26c6f992cc11/src/destreamer.ts#L83
Just change the timeout (in milliseconds) to what you'd like

You can always tell Destreamer the username you'd like to fill in with the '-u' option

Sorry for the quick response, when I'll be home this evening I'll expand on my response

**Comment by mavink** [comment]
Yes I do know that I can increase the timeout, but the point was to avoid typing, not spend all the time typing :)

Yes originally I built the gui to send in the username with -u to destreamer, but I gave up on that when there was no clean way to send the password also. And also that hack will require that the css selector you use to send the username remains stable. 

Would prefer to use existing standard GUIs as far as possible. Chrome offer a very good standard GUI. In fact nothing will be better if this code makes it as a Chrome or Firefox extension rather than this unseemly workaround using an automated browser.. just like youtube video downloader extensions for Firefox and Chrome.

**Comment by lukaarma** [comment]
> Or is there a reason why you don't want puppeteer Chrome to also autofill and save passwords?

Security. If we don't have any password saved anywhere there's (almost) no security risk for the user

> Microsoft sometimes decides to ask you to login again randomly. Maybe because they're signed in to many devices

It's still happening even if you use the latest version using the '-k' option?

> Yes originally I built the gui to send in the username with -u to Destreamer, but I gave up on that when there was no clean way to send the password also

Since the troubling part of your kids login is the long username I think it's wort wile to use the '-u' option

> And also that hack will require that the css selector you use to send the username remains stable.

That's also true for any password fill-in logic we could implement... so what's your point?

> Would prefer to use existing standard GUIs as far as possible. Chrome offer a very good standard GUI. In fact nothing will be better if this code makes it as a Chrome or Firefox extension rather than this unseemly workaround using an automated browser.. just like youtube video downloader extensions for Firefox and Chrome.

Those extensions work great because you only download a couple of videosa, Destreamer it's built to do bulk operations since our users are mainly students/workers that may have to download 10s of videos in one go.

---

I'm sorry but I don't see a good reason why I should enable chrome to save the users password or build a password fill-in logic in Destreamer, especially since the last update where I added the chrome cache and session refreshing to extend the one hour lifetime of the token.
If you really want any of those feature you could do it yourself, maybe even publish you fork to the public, or you could ask @snobu or some other developer but I'm not going to enable such logic,
I'm really sorry but I hope you can understand my view on this security issue and why I son't want to do such an update
