### ISSUE TITLE
Create title template

### ISSUE THREAD

**Issue by lukaarma** [snobu/destreamer#190]
As per title, see this [comment ](https://github.com/snobu/destreamer/issues/175#issuecomment-657049293) for more info

[BUG] Also add a unique id to create more unique filenames (see #176)

**Comment by lukaarma** [comment]
@snobu any idea on how to implement this in a right way? Because I've drew blanks for 2 hours now, all bad and hackish implementations :/

**Comment by peppelongo96** [comment]
@lukaarma In order to more unique filename, the fastest walkable way reamins adding current download timestamp as video ID.
BUT I think that also hours and minutes of video upload could be used "unique" identfier. Because of we can't get them from blob stream, I have a strange idea for how to do. 
Stream autogenerates the common black splashscreen video with title and video info. So we could take a screenshot of it and using a free OCR to recognize the text, and so the upload time of the video.
There's an example here using the first site I found, but there are hundread of free OCR API that can we use:

 [
![Cattura](https://user-images.githubusercontent.com/43895223/88347217-8ae8ad80-cd4a-11ea-9261-9246df12d981.PNG)
](url)

Now the good question is if worth it or not.

**Comment by lukaarma** [comment]
The unique id it's the easiest part: `guid -> sha-1 -> random 8 char substr` 
I think it's random enough that on a small set like all the videos a user can download we won't have any problems with collision

It's the output template that I'm having trouble with

**Comment by beppe9000** [comment]
maybe we could look for templating libraries ?

**Comment by snobu** [comment]
```
--out-filename "$date - $title - $owner"
```

Why not keep it simple?
We could have three parameters and let users build their desired filename out of it.
In out templating code we then simply look for `$title` and replace with the title we get from the API call.

**Comment by beppe9000** [comment]
Yes, that is a good idea. Maybe make a dictionary of avaliable tokens. What I think needs some attention is the fact that this is a CLI tool so identifiers or characters that could be interpreted by the shell should be avoided. I don't know enough about linux but my understanding is that on bash the `$value` denotes variables. Maybe using a `@`, reducing my initial template format idea to something simpler without additional formatting parameters.

**Comment by snobu** [comment]
Wrapping things in double quotes would escape shell parsing, but i agree, `{title}` looks better as a parameter.

**Comment by lukaarma** [comment]
if the user inputs a bad/misspelled parameter such as {titl} should we error out, remove the bad param or just warn the user and leave it as text?

**Comment by snobu** [comment]
Let's walk the input string twice, once replacing all known variables, second pass (with variables replaced) check if there's still any `{something}` (regex?) and error out. To be honest this won't be as trivial as it may sound so for now i'd say just skip the second pass. Let's just replace what we advertise™.

**Comment by lukaarma** [comment]
The idea I was coding was a first check during the argv parsing thanks to
yargs to sanitize the template so that when it comes to actually using it
we just need to replace the {elements} without any worries

**Comment by lukaarma** [comment]
| element name 	| -> 	|        source       	|
|:------------:	|----	|:-------------------:	|
|     title    	| -> 	|    videoInfo.json   	|
|   duration   	| -> 	|    videoInfo.json   	|
| publish date 	| -> 	|    videoInfo.json   	|
|   uniqueID   	| -> 	| generated from guid 	|

**Comment by lukaarma** [comment]
any other idea for template elements and where can we get them?

**Comment by beppe9000** [comment]
> if the user inputs a bad/misspelled parameter such as {titl} should we error out, remove the bad param or just warn the user and leave it as text?

I'd normally prefer just a big yellow warning, but I think since this tool implies a lot of wasted time renaming bulk downloaded stuff if the parameter is not correct it may be better to error out, so the user is guaranteed proper file naming. for this a regex like `{(/w+)}` and then print the unrecognized tokens in the error

**Comment by lukaarma** [comment]
> maybe another token could be a human readable timestamp: `{ts} => YYYYMMDDHHMMSS`

timestamp of what?

**Comment by beppe9000** [comment]
> timestamp of what?

publish time

> actually I'm using this `/{(.*?)}/g` regex, i think it's better because it cover any bad input the user tries to put between curly brackets

yes much better

**Comment by lukaarma** [comment]
> publish time

we have publish date and time in the table

> I think since this tool implies a lot of wasted time renaming bulk downloaded stuff if the parameter is not correct it may be better to error out

with this you mean that since it's usually used to download a lot of videos we could save the user a lot of hand edit if we error out instead of warning the user and let him take action if he wants?
@snobu your take on this?

**Comment by snobu** [comment]
Well, since the user has explicitly told us they want to use the template via whatever parameter name we decide upon i'd say error out if the trmplate format is invalid. An exir code of its own is desired here.
