### ISSUE TITLE
Changing the Browser

### ISSUE THREAD

**Issue by aaronjohnsabu1999** [snobu/destreamer#206]
Every time I use _destreamer_, I have to log into my Microsoft school account, which only permits 10 instances. This seems to be a difficult task to deal with. How can I change the browser for _destreamer_ to MS Edge or Google Chrome? I guess there should not be any issues since both browsers are based on Chromium.

**Comment by lukaarma** [comment]
You can check out the -k option here that saves the cookies so that once you login it wont as it again, see [here](https://github.com/snobu/destreamer/issues/190#issuecomment-666152780)

f you really want to change it to your installation of chrome you can do so changing this line
https://github.com/snobu/destreamer/blob/5b62c50b220b1e784bd21654f634105e78249c76/src/PuppeteerHelper.ts#L20
to be `return /PATH/TO/EXE` where PATH is the path of your chrome executable

**Comment by aaronjohnsabu1999** [comment]
Thanks. I realized this from [#204](https://github.com/snobu/destreamer/issues/204).
Thanks for the flexibility of the package!
