### ISSUE TITLE
Add random ID to filenames

### ISSUE THREAD

**Issue by klenium** [snobu/destreamer#21]
A lot of our video conference is just automatically uploaded to Streams, and no one cares their title, so all titles are simply "Meeting in General". This will cause error if I try to specify more than one `--videoUrls`. Maybe you should append the video ID to the output filename, that is unique.

**Comment by lukaarma** [comment]
Another possibility is to check if the same filename exists in the video folder and post pone a number, because the video id would add 15-20 char to the file name.
Or we can prepend a number to the filename if there are multiple of the in the same download.

I'll look into it when i have some free time

**Comment by snobu** [comment]
Thanks for reporting this. Let's first understand exactly what breaks. @klenium do you see this in the log?

```
[download] file.mkv has already been downloaded and merged
```

If you don't, what's the error that gives away the problem? I'm trying to understand if it breaks in our code or is it youtube-dl that panics.

**Comment by klenium** [comment]
Yes, I saw that line. I specified 4 links, but had the same title, so only the first one was downloaded, then the script exited.

**Comment by snobu** [comment]
Great, then i propose a method that takes the array of video URLs from the command line, sanitizes titles, deduplicates them by appending the first few chars from the video GUID and returns back a sane array to our application code.

Needs to be added after we merge https://github.com/snobu/destreamer/pull/20 since there's a lot of change happening there.

**Comment by lukaarma** [comment]
Solved merging #28
