### ISSUE TITLE
Question about downloads

### ISSUE THREAD

**Issue by Dunsteer** [snobu/destreamer#231]
Will the owner know I downloaded the video through destreamer or not?

Thanks.

**Comment by lukaarma** [comment]
The owner (mostly) won't know that you downloaded the video :)

**Comment by snobu** [comment]
To be clear, we're using the same protocol (HLS) as a browser would when 'interactively' playing a video. For all intents and purposes we're just another browser as far as MSStream is concerned.

However don't forget this is still operating in a grey area, the owners of the video may not want you to be able to download it, however since you are able to play it in a browser this now opens the door to a philosophical debate about the meaning of life, ownership, the universe and everything.

**Comment by Dunsteer** [comment]
I went trough the same thought process when I was asking the question.
