### ISSUE TITLE
some errors i get

### ISSUE THREAD

**Issue by AndrewAtef17** [snobu/destreamer#26]
sometimes i get some of this error but it continue downloading, the video lose some parts at the end:
[tcp @ 000002401db659c0] Connection to tcp://gd5xbgutd55iu6wqwypmuwj5ad.streaming.mediaservices.windows.net:443 failed: Error number -138 occurred
[crypto @ 000002401ddcd640] Unable to open resource: https://gd5xbgutd55iu6wqwypmuwj5ad.streaming.mediaservices.windows.net/a9f646e5-f1dc-49d4-b1ea-1b128677e6df/1-ipd7237ui44zx2bs2rjvad6y6g.ism/QualityLevels(250000)/Fragments(video=1260000000,format=m3u8-aapl)[hls @ 000002401d8aefc0] Failed to open segment 21 of playlist 0

also i get sometimes this error and the program closes:
"Navigating to STS login page...
We are logged in. Got cookie. Consuming cookie...
Accessing API...
Fetching title and HLS URL...
Error when calling Microsoft Stream API:403"

Note : the last error i started to get only after your latest changes in destreamer.ts

**Comment by constructor-s** [comment]
Confirming the same error on macOS 10.5.3 with latest commit https://github.com/snobu/destreamer/commit/ee1d9b3cf1436b25f8fe11d0dc0f9665e7afea3e

```
Using youtube-dl version 2020.03.24
Using ffmpeg version 4.2.2 Copyright (c) 2000-2019 the FFmpeg developers
Launching headless Chrome to perform the OpenID Connect dance...
Navigating to STS login page...
We are logged in. Got cookie. Consuming cookie...
Accessing API...
Fetching title and HLS URL...
Error when calling Microsoft Stream API:403
{
  error: { code: 'Forbidden', message: 'The user has not been provisioned' }
}
Exiting...
```

**Comment by constructor-s** [comment]
@snobu Looking at https://github.com/snobu/destreamer/blob/ee1d9b3cf1436b25f8fe11d0dc0f9665e7afea3e/destreamer.ts#L198-L200, I think more work needs to be done on the API endpoint discovery to make it universal. 

By manually testing in my browser, I found my endpoint is `cact-1.api.microsoftstream.com`, i.e. `
https://cact-1.api.microsoftstream.com/api/videos/VIDEO_ID?$expand=creator,tokens,status,liveEvent,extensions&api-version=1.3-private
`
works fine for me. 

`api.microsoftstream.com` and `use2-2.api.microsoftstream.com` gives me 401. `cact-1-content.api.microsoftstream.com` gives me 403. Haven't looked into why the code reports error 403 instead of 401. 

I am not familiar with `puppeteer`, but I assume there might be a way to automatically discover this? Right now I found these by looking at the network activity.

**Comment by constructor-s** [comment]
I confirm that after changing https://github.com/snobu/destreamer/blob/ee1d9b3cf1436b25f8fe11d0dc0f9665e7afea3e/destreamer.ts#L200 to my appropriate endpoint, the program works as intended.

**Comment by constructor-s** [comment]
When viewing the HTML source code for `https://web.microsoftstream.com/video/VIDEO_ID` the only place where the API endpoint is specified is in the `<script>` inside `<head>` in a JSON string `"ApiGatewayUri":"https://cact-1.api.microsoftstream.com/api/"`

A quick regex could do the job, but is there a more JavaScript-esque way?

**Comment by lukaarma** [comment]
Ok I should have a fix in my local versione, as soon as I'm ready to push and open a pull request I'll reference this issue

**Comment by snobu** [comment]
Thank you for reporting this. I fixed it in the latest commit. Pull, transpile and try again, the correct API URL should be pulled from your session info rather than hardcoded.

Feel free to reopen if trouble persists.
