### ISSUE TITLE
ffmpeg slower than youtube-dl

### ISSUE THREAD

**Issue by sasopenna** [snobu/destreamer#88]
I'm the only one that with this method has slower downloads? With the youtube-dl method i've downloaded 300mb files within 1 hour, now for 30mb files it takes more than 1 hour and a half.
Maybe it's my computer? The bitrate of the download is always from 100kbits/s to 240, never gets higher. My internet speed in download is always around 2mb/s or more, i don't know whats the problem. Someone could help me?

**Comment by snobu** [comment]
You can still use the old version of destreamer (just clone the `dev` branch instead). Let us know if there's any improvement in download speed.

**Comment by sasopenna** [comment]
I don't know how or why but it became faster from absolutely touching nothing. Thx for the answer btw great project :)

**Comment by kylon** [comment]
youtube-dl uses ffmpeg under the hood, so this cannot be slower

moreover, speed depends on other things other than destreamer itself

**Comment by sasopenna** [comment]
> youtube-dl uses ffmpeg under the hood, so this cannot be slower
> 
> moreover, speed depends on other things other than destreamer itself

Yeah I saw that the last version was youtube-dl + ffmpeg, but I don't know why this version seems slower, and the video result of 1 hour of streaming sometimes is 50MB, maybe it's my PC/Internet, because everything works fine at the end of the day.

**Comment by kylon** [comment]
Comparing my videos info i see no differences other than the resolution
some are 720p, others 1080p

so i think we can suppose we all wasted a lot of space because of youtube-dl, ffmpeg (or fussonia), is using good default settings

i don't know the full ffmpeg command of youtube-dl, and now, ffmpeg videos are probably compressed, but since i see no difference in quality, this is welcomed (also there are good compression algos out there that can save a lot of space while keeping the best quality)

and i trust ffmpeg ;)

**Comment by FraH90** [comment]
I also had the sensation that with the new branch the download is slow, compared to the old version (dev).
Don't know if it's just a feeling, or is really a thing.

About quality, even if I'm still downloading with the older version I've seen that there's no difference in quality of the download.. I mean, videos weight less but quality seems the same (visually, dont know technically which one is better)

**Comment by sasopenna** [comment]
Yeah, nothing to say about the quality, because is good even if the weight is less than before. As I already said, in my case I've waited more than 1 hour and the result file was 50mb, but the video is in really good quality. I think it's doing some compression under the hood that's why it seems slower. Anyway it's a good work and as I said maybe it's my computer that can be responsible for this.

**Comment by kylon** [comment]
i can't try, but you can download the same video with both old and new destreamer at the same time, if there is a huge difference in speed, maybe yeah, we are missing something

about quality, again, there is NO difference, file size is not the way to misure quality in any way.
current sizes are correct, if your video was 300mb before, and now it is 50mb, it means there was a huge problem with youtube-dl

@snobu 
can you please add a note about this to changelog, we now have the correct compression and no quality downgrade, youtube-dl settings were bad

**Comment by snobu** [comment]
I don't want to point fingers at any other open source project for doing things the way they do it especially since we had a hard dependency on it :) I'm sure everyone has their very good reasons when they pick their defaults.

Now, to the drawing board.

I picked a random video which has HLS bitrate levels up to 5Mbps 1080p.
Straight from the m3u8:
![image](https://user-images.githubusercontent.com/6472374/80290596-ec4eaf80-874e-11ea-8111-4ea2634b8dad.png)

We download that video using the master branch (destreamer v2.0) and a recent ffmpeg (4.2.2) -
```
$ mediainfo '.\videos\The New Yammer - 02-11-2019.mp4' | grep "Bit rate" -A 3
Bit rate                                 : 3 493 kb/s
Width                                    : 1 920 pixels
Height                                   : 1 080 pixels
Display aspect ratio                     : 16:9
```

Bitrate is a little more conservative after the encoding/muxing step but we're at the same 1080p as the original.

So, i wouldn't go as far as to say youtube-dl did a poor job, they probably just passed a bunch of quality parameters down to ffmpeg that made things look differently on disk.

![image](https://user-images.githubusercontent.com/6472374/80290532-4307b980-874e-11ea-959b-f540dbbde630.png)

**Comment by snobu** [comment]
There's also a `map` parameter we could pass to ffmpeg to target a different bitrate stream, we can decide on that after we evaluate aria2c first.

**Comment by kylon** [comment]
i'm not saying it did a poor job, but for ex. my videos are almost a bunch of static images, that is where compression shines with no compromises

90% of the size of my videos is the audio and i'm sure it is the same for all those people who now have smaller videos

youtube-dl did a poor job here, if/when we switch to aria, i think it is better to keep this behaviour (or settings?) as default (hdd space is limited)
we actually never thought about this
